### PR TITLE
[GTK] Show a message box for unhandled exceptions

### PR DESCRIPTION
**Pull request by InfinityGhost**

### CODE REVIEW

**Review by Sublimelime — APPROVED** [review]
Could this be done for Windows and MacOS as well?

**Comment by jamesbt365** [comment]
This is more to show in linux which error has happened. Don't really see how this specifically matters for other platforms. Maybe something in another pr if you can think of anything?

**Comment by InfinityGhost** [comment]
It's certainly doable (via `AppDomain.CurrentDomain.UnhandledException`) however on GTK it has to be done this way.

**Comment by Sublimelime** [comment]
Would it even be worth doing though, I haven't done a ton of work with the windows/mac side of things. Do those two crash "cleaner"?

**Comment by InfinityGhost** [comment]
There's really no downside to adding it. GTKSharp has its own exception manager that bypasses CurrentDomain somehow, I'm not sure if WPF or mac does this.

**Pull request merged**
