### PR TITLE
[0.6.x] MacOS pressure (AkiSakurai's `tabletmore` branch)

### PR DESCRIPTION
**Pull request by gonX**
Unofficial backport of #2894. Will need testing.

From original post:
> Dedicated artist mode seems unnecessary for macOS as it does not change the behaviour like Windows Ink.
>
> The tilt functionality has not been tested with a real device, so the scale normalisation may differ from that of the official driver.

### CODE REVIEW

**Comment by gonX** [comment]
I can't request a review from someone out-of-org but maybe you can verify that this looks fine @AkiSakurai ?

**Review by Kuuuube — APPROVED** [review]
@TheSevenPens tested this and it works perfectly. Running on Apple M3 Pro and Sequoia 15.1.1. Would be nice to pull this in for 0.6.5.

**Comment by gonX** [comment]
Sounds good to me. I would like an additional review if possible, given the size of the PR.

**Review by InfinityGhost — APPROVED** [review]
lg2m

**Pull request merged**
