### PR TITLE
Add support for Wacom CTC-x110WL

### PR DESCRIPTION
**Pull request by Kuuuube**
~~Awaiting confirmation on CTC-6110WL~~

Confirmed working on CTC-4110WL and CTC-6110WL

### CODE REVIEW

**Review by InfinityGhost — APPROVED** [review]

**Comment by TheRacc2** [comment]
Could this be merged? I'm currently using a CTCW1AB which should be detected by this commit.

**Comment by wei1769** [comment]
> Could this be merged? I'm currently using a CTCW1AB which should be detected by this commit.

I'm still waiting too, but if you are using windows someone compiled a version of this branch and put it in discord

**Comment by jamesbt365** [comment]
Just use this:
https://cdn.discordapp.com/attachments/1162123077619036241/1162129874916474951/CTC-x110WL_build.7z?ex=65568049&is=65440b49&hm=7568d40308da8e17fc143fb9be9516dc9251020c8151141c30c21a15cacb4819&

Merging won't do what you think it is going to do, its still not going to be in a release until another hotfix release drops, this will be merged before that point, so this being merged now reasonably changes nothing. The code you are looking at here is for 0.7 a staging dev branch which is unstable and not suitable for daily use for most people, it will be merged and backported as an when a new release is ready to drop.

**Comment by TheRacc2** [comment]
I just built it myself, as I don't exactly trust a random discord link.

steps for the average (windows) user:

```
[1] Install git and dotnet 6.0
[2] open Powershell (Win+R, type "powershell" and hit enter)
[3] Navigate to any location (for most users, type "cd ~/Desktop")
[4] type "git clone https://github.com/OpenTabletDriver/OpenTabletDriver"
[5] type "git fetch"
[6] type "git pr 2902"
[7] type "cd OpenTabletDriver && ./build.ps1"
[8] when finished, open "OpenTabletDriver/bin/OpenTabletDriver.UX.Wpf.exe" on your Desktop
```

**Comment by jamesbt365** [comment]
going to give a list of instructions that will work *regardless* of if you have github extensions for git and that are actually in a proper order (the commands you linked are not at all in order, you can't fetch, switch branch or anything without being in that directory).

Also this isn't an "ideal" situation anyway due this being based on master, as I said previously, master is an unstable branch, it is far more unstable than any release build is, and the build I linked (that was built by a developer, a user related to and is on the OpenTabletDriver organisation)  so I highly recommend any users use that over building something based off master.

I will not get into the process of installing git or the dotnet **7** sdk. You need 7 because this is master.
```bash
git clone https://github.com/Kuuuube/OpenTabletDriver
cd OpenTabletDriver
git checkout intuosv3
# Set-ExecutionPolicy unrestricted 
# Please understand what this is doing before running the command above.
# This will remove the restrictions on running powershell scripts allowing any script to run.
# I recommend you set this back to Restricted unless you are running powershell scripts often.
.\build.ps1
```

The binaries will be in the `bin/` folder after.

**Comment by liam-lemonade** [comment]
thanks for the updated response 🙇 i threw it together with not a lot of effort

**Pull request merged**
