### PR TITLE
Change macos info.plist string

### PR DESCRIPTION
**Pull request by jamesbt365**
Based off here: https://discord.com/channels/615607687467761684/628651971267788800/980630394548416573

### CODE REVIEW

**Review by gonX — APPROVED** [review]
My suggestion, and reverse DNS is the typical solution: https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier

**Comment by jamesbt365** [comment]
File is gone now :P

**Comment by InfinityGhost** [comment]
> File is gone now :P

Bring this file back as it was unintentionally removed.

**Comment by jamesbt365** [comment]
File has been restored with the plist string change

**Comment by X9VoiD** [comment]
Info.plist was moved to packaging scripts.

**Pull request closed without merging**
