### PR TITLE
Add support for XP-PEN MT0960B (deco pro sw)

### PR DESCRIPTION
**Pull request by jamesbt365**
https://canary.discord.com/channels/615607687467761684/615611007951306863/993964520261288088

### CODE REVIEW

**Review by X9VoiD — CHANGES_REQUESTED** [review]
The name in configuration and TABLETS.md does not match.

**Comment by jamesbt365** [comment]
Resolved

**Review by X9VoiD — CHANGES_REQUESTED** [review]
Use the other name, this is not even searchable by Google. In the future there should be a way to refer to the tablets via their "marketing name" if it exists.

**Comment by jamesbt365** [comment]
Either will cleanup the tablets.MD in a feature PR or I can add the other name in brackets now?

**Review by X9VoiD — APPROVED** [review]

**Pull request merged**
