### PR TITLE
Reduce bloat of tablet configuration JSONs

### PR DESCRIPTION
**Pull request by X9VoiD**

### CODE REVIEW

**Review by jamesbt365 — APPROVED** [review]

**Review by Kuuuube — APPROVED** [review]

**Review by gonX — APPROVED** [review]
Code seems good, didn't check jsons too in depth tho, but what I saw also made sense to me.

**Comment by gonX** [comment]
Out of curiosity, what happens if a user uses a config with the old specifications? Will it still load?

**Comment by X9VoiD** [comment]
It's only the tests that enforces that they be null, so whether the config defines nothing, null or is set to an empty array, they will still load.

**Comment by gonX** [comment]
Good enough for me, merging.

**Pull request merged**
