### PR TITLE
Add support for CTL-4100WL wireless mode

### PR DESCRIPTION
**Pull request by jamesbt365**

### CODE REVIEW

**Comment by jamesbt365** [comment]
Turns out this needs a new praser, probably.

**Comment by Kuuuube** [comment]
Position appears to be reported differently. Second byte also needs to be checked instead of the first byte.

**Comment by harrisonthorne** [comment]
hey y'all, out of curiosity, do you know if this will also make Bluetooth work on my Wacom PTH-660 (Intuos Pro M)?

**Comment by IllustratedMan-code** [comment]
Any updates on this?

**Comment by jamesbt365** [comment]
No.

**Comment by IllustratedMan-code** [comment]
The website should be updated then. https://opentabletdriver.net/Tablets?search=wl says that ctl-4100wl is supported

Also, happy to test anytime

**Pull request closed without merging**
