### PR TITLE
Fix wheel support for Gaomon M6

### PR DESCRIPTION
**Pull request by X9VoiD**

### CODE REVIEW

**Review by InfinityGhost — APPROVED** [review]
lg2m

**Comment by nukawa** [comment]
Sorry to bother you, I tried to adopt OpenTableDriver for my Gaomon M6 first time.
That is a good experience for me so far. However, these are too difficult to me due to a brand new Linux user, could you help to teach me or tell me the related information to adopt these materials as above? Thanks a lot.

**Comment by X9VoiD** [comment]
OTD doesn't support configuring and binding to wheels yet, only parsing.

**Comment by nukawa** [comment]
Thanks for your reply, I will keep waiting the following update, thanks a lot.

**Pull request merged**
