### PR TITLE
Switch AreaDisplay to standard Drawable

### LINKED ISSUE #2609: High CPU usage after minimizing on "output" tab
### Acknowledgements

- [x] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

case 1:
start otd and minimize it

case 2:
start otd, select "filters" tab and minimize it

### Expected Behavior

0% cpu usage in a minimized app that does nothing

### Observed Behavior

case 1:
3% of cpu usage

case 2:
0% of cpu usage

### Tablet Device

ctl-470

### Diagnostic Information

[jason.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10419469/jason.txt)

### LINKED ISSUE #2637: Take all of my RAM on Pop! OS
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1: Open the application
2: Minimize the application and see that the ram goes up
3: Then after some times, the application take all of my 32Go of ram.
[open_tablet_driver_ram.webm](https://user-images.githubusercontent.com/97894103/218581673-74799d99-8001-44e3-babf-d8583acbedf9.webm)
Capture d’écran du 2023-02-13 22-59-12

### Expected Behavior

The ram usage should be normal

### Observed Behavior

The ram usage goes up with time to fully take all of my 32go of ram

### Tablet Device

Wacom CTL 472

### Diagnostic Information

[file.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10726597/file.txt)

### PR DESCRIPTION
**Pull request by InfinityGhost**
- May fix #2637
- Fixes #2609

### CODE REVIEW

**Review by X9VoiD — CHANGES_REQUESTED** [review]
The `Drawable` is never invalidated, so it's never redrawn again.

**Review by X9VoiD — APPROVED** [review]
I still believe `ScheduledDrawable` shouldn't be a thing anymore, but that can be on another PR.

**Comment by InfinityGhost** [comment]
> I still believe `ScheduledDrawable` shouldn't be a thing anymore, but that can be on another PR.

[`TabletDebugger`](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/1055733d8c030078c79e6c35f043be43c2fd59cb/OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs#L306) depends on `ScheduledDrawable`.

**Comment by X9VoiD** [comment]
Not enough of a reason to keep it. It just calls `Invalidate()` on a timer that is locked to 60fps.

**Pull request merged**
