### PR TITLE
Move non-english readmes into docs folder

### PR DESCRIPTION
**Pull request by Sublimelime**
De-clutter project root, make more use of the docs/ subfolder created initially for the manpage.

### CODE REVIEW

**Comment by vedattt** [comment]
Also consider moving `CONTRIBUTING.md` into `.github`.

**Comment by vedattt** [comment]
Also consider moving `TABLETS.md` into `docs`.

**Review by gonX — APPROVED** [review]

**Comment by gonX** [comment]
> Also consider moving CONTRIBUTING.md into .github

Disagree, it's an essential file that I think a couple of people expect in the project root, together with a readme and license.

> Also consider moving TABLETS.md into docs

I don't mind this but this can easily become its own PR

**Comment by Sublimelime** [comment]
> Also consider moving TABLETS.md into docs

> I don't mind this but this can easily become its own PR

I didn't do this because of how the site works - it looks for tablets.md in the root directory, so if I were to move it the website would need fixing too. It's also not documentation in my eyes, more like a feature list - doesn't really belong in `docs`.

**Comment by Sublimelime** [comment]
Merge conflicts resolved, should be good for merge now.

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
