### PR TITLE
Re-enable self-contained publishing

### PR DESCRIPTION
**Pull request by X9VoiD**
and trim assemblies to cut down file size.

- Depends on #1441

Final file sizes are around 30Mb.

### CODE REVIEW

**Comment by InfinityGhost** [comment]
I'd really prefer to not do self contained publishing. The filesize may be smaller now, but we've had multiple issues because of self contained executables.

**Comment by X9VoiD** [comment]
We actually have more problems with non-self-contained assemblies (look at Discord's #help-windows and Gentoo) than self-contained. The only problem we had with self-contained publishing was big file size afaik.

**Comment by InfinityGhost** [comment]
I'm really against building this self contained. I'd rather stick to our current process, the filesize is too much to justify.

**Comment by X9VoiD** [comment]
Bringing this PR back as this is the recommended deployment model for .NET apps and it solves way many headaches for everybody. The file size is only around 30MB, not as big as you're making it out to be.

**Comment by gonX** [comment]
Would be cool if you could squish commits a bit, so we don't get 16 commits for something that should be 1 or 2 commits (not to mention the .NET 6 change which we've already had).

Can someone explain the issues we had when we did use self-contained publishing?

**Comment by X9VoiD** [comment]
No issues other than nix breaking as reported by @InfinityGhost, and file size.

We don't have to worry about type removal since all of those types are plugin types within OTD. Assemblies from OTD doesn't participate with assembly trimming because `IsTrimmable` is [false by default](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#enable-trimming).

**Comment by gonX** [comment]
Thanks. I'm still requesting a commit squish though ;)

**Comment by X9VoiD** [comment]
Too much reflection on latest master to make this work again.

**Pull request closed without merging**
