### PR TITLE
Added Greek Readme

### PR DESCRIPTION
**Pull request by JohnVictoryz**
Added greek in readme.md but also translated to greek the readme

### CODE REVIEW

**Comment by jamesbt365** [comment]
README translations must be on all files so you need to update the other README files to include your own in the list of languages.

**Comment by JohnVictoryz** [comment]
> README translations must be on all files so you need to update the other README files to include your own in the list of languages.

KK fixing this i will close this pull request now

**Comment by jamesbt365** [comment]
Why did you close it? Just add a commit?

**Comment by JohnVictoryz** [comment]
how to undraft ???

**Comment by JohnVictoryz** [comment]
found it

**Comment by jamesbt365** [comment]
Squash commits please

**Comment by JohnVictoryz** [comment]
> Squash commits please

how can i do that

**Pull request closed without merging**
