### PR TITLE
Added Tilt support for Veikk tablets

### PR DESCRIPTION
**Pull request by brkeejp**
Added: Tilt support for Veikk tablets on TabletParser file.
Added: Aux buttons support for Veikk VK640

Tested: Aux buttons support for Veikk VK640
Tested: Tilt support for Veikk VK640

### CODE REVIEW

**Comment by brkeejp** [comment]
Well I'm not sure how to use Github.
Looked Contribute guide and it's says take config branch as base and I do so.

**Comment by jamesbt365** [comment]
Not what i meant but okay. I said why did you include the configuration change and tablets.md change as they are already included in another pull request

**Comment by jamesbt365** [comment]
Also the formatting is not right, aux won't work.

**Comment by brkeejp** [comment]
Ohhh you mean that. Like I said, dunno how to use git. And looks like your request marked draft.
Also like I stated contribute guide says take most recent config branch as base, soo I didn't looked anywhere other.
Should I close request and take your as base?

**Comment by jamesbt365** [comment]
You took the right base you just committed the changes from my branch in one commit, effectively squashing the commit.

**Comment by brkeejp** [comment]
I didn't do it intentional, don't know what to do. so going to close this request feel free to include my tiny edit.

PS: Just in case I don't know what is returning tilt range, so did left untouched which is -128 to +128. 1/1 degree per value.
Where limited to 70~ degree for VK640

**Pull request closed without merging**
