### PR TITLE
Change "Pressure" to "Threshold" on the bindings tab

### PR DESCRIPTION
**Pull request by jamesbt365**
Changed pressure to deadzone in the bindings tab in otd to reduce confusion.

### CODE REVIEW

**Comment by gonX** [comment]
I agree that pressure isn't the best wording, however I think we can do better than deadzone...

Maybe just use the wording "pressure threshold" or simply "threshold" instead of deadzone?

**Comment by jamesbt365** [comment]
Converted to Threshold.

**Comment by InfinityGhost** [comment]
This patch is all that is needed for the migration to work as intended. Existing settings (on master) will not be migrated, however as a development version I don't care that it won't be.
```diff
diff --git a/OpenTabletDriver.Desktop/Migration/SettingsMigrator.cs b/OpenTabletDriver.Desktop/Migration/SettingsMigrator.cs
index 0137a87c..4ae4aa24 100644
--- a/OpenTabletDriver.Desktop/Migration/SettingsMigrator.cs
+++ b/OpenTabletDriver.Desktop/Migration/SettingsMigrator.cs
@@ -62,6 +62,7 @@ namespace OpenTabletDriver.Desktop.Migration
                         }
                     )
                 );
+                profile.BindingSettings.TipActivationThreshold = old.TipActivationPressure;
                 profile.BindingSettings.PenButtons = SafeMigrateCollection(old.PenButtons);
                 profile.BindingSettings.AuxButtons = SafeMigrateCollection(old.AuxButtons);
             }
```

**Comment by jamesbt365** [comment]
should be good to go.

**Comment by jamesbt365** [comment]
should be good to go now.

**Comment by gonX** [comment]
> Existing settings (on master) will not be migrated, however as a development version I don't care that it won't be.
What would be needed to make this possible on master? Alternatively, is the user informed of settings being dropped?

**Comment by InfinityGhost** [comment]
> What would be needed to make this possible on master?

We would need some sort of versioning system for settings, which quickly becomes messy.

> Alternatively, is the user informed of settings being dropped?

Nope, it should just be filled with defaults instead. Might be worth doing in another PR.

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
