### PR TITLE
Add backup directory for settings and migration

### LINKED ISSUE #1948: OTD wipes temp folder after updating
## Description

Instead of moving all files (except userdata) from the previous version's folder to `userdata\Temp\0.6.0.0-old\bin\` and leaving them there they get wiped as soon as OTD starts.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Win10
| OpenTabletDriver Version | 707f71ec9399056dddd8cfb6d94d0680b0b1c9f5

### PR DESCRIPTION
**Pull request by InfinityGhost**
This resolves the situation where backups are stored within volatile temporary directories. This unifies all backups to a single directory.

- Closes #1948

### CODE REVIEW

**Review by X9VoiD — APPROVED** [review]

**Review by Kuuuube — APPROVED** [review]
Works.

Tested on Win10.

**Comment by Kuuuube** [comment]
Actually, got an error when trying to overwrite files. Might also need to handle if a file is locked by windows and can't be overwritten too.
[error.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7873984/error.txt)

**Comment by Kuuuube** [comment]
Put the wrong error log in my previous comment. Here are the correct ones:
[error1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7874004/error1.txt)
[error2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7874003/error2.txt)

**Comment by InfinityGhost** [comment]
> Put the wrong error log in my previous comment. Here are the correct ones: [error1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7874004/error1.txt) [error2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7874003/error2.txt)

I'm unable to reproduce this in my win11 virtual machine.

**Review by Kuuuube — APPROVED** [review]
Looks good. Everything works.

Tested on Win10.

**Pull request merged**
