### PR TITLE
Prevent infinite exceptions from UX when daemon disconnected

### LINKED ISSUE #2028: Infinite Message boxes are shown when daemon is crashed.
## Description

Log.Exception is called when unhandled exception happens.
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/502589660232add52a1ae7bd7de584e7192f2ec2/OpenTabletDriver.UX/App.cs#L128

The output handler of Log is async function without try-catch.
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/34f27af7e1b14591fc7832f1527699e93d83454d/OpenTabletDriver.UX/MainForm.cs#L329

Output handler is invoked without await, so exception happens inside WriteMessage cant be catched.
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/caf21a15b3130fe85e02255099e126b36e154406/OpenTabletDriver.Plugin/Log.cs#L19

ShowUnhandledException is invoked again to handle unhandled exception from WriteMessage.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | MacOS
| OpenTabletDriver Version | 0.6.0.2

### PR DESCRIPTION
**Pull request by vedattt**
## Changes

- Check if RPC client is connected to the daemon before trying to send it a log message to print.
It makes sense to check only the daemon output handler rather than the `ShowUnhandledException` method as `Log.Output` may have sensible handlers that should run even if daemon is dead.

## Issues

- Closes #2028

### CODE REVIEW

**Comment by AkiSakurai** [comment]
Null checking is not useful.
This is the exception it throw.
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'StreamJsonRpc.JsonRpc'.
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue, String message)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at OpenTabletDriver.UX.MainForm.<>c.<<HandleDaemonConnected>b__11_1>d.MoveNext() in /Users/shawn/Desktop/Study/otd/OpenTabletDriver/OpenTabletDriver.UX/MainForm.cs:line 333
  ```

**Comment by vedattt** [comment]
@AkiSakurai Trying an exception-based approach. Could you try reproducing with this build?

**Review by AkiSakurai — COMMENTED** [review]
The exception is not catchable here.

https://stackoverflow.com/questions/53215577/why-does-exception-from-async-void-crash-the-app-but-from-async-task-is-swallowe

**Comment by vedattt** [comment]
> The exception is not catchable here.

@AkiSakurai Catching the exception left a bit of a sour taste anyway, I ended up exposing the internal RPC connection status. Have a look.

**Comment by AkiSakurai** [comment]
It works.

**Comment by vedattt** [comment]
Nice! Thanks for confirming.

**Review by InfinityGhost — APPROVED** [review]
lg2m

**Pull request merged**
