### PR TITLE
Add UGTABLET M708 configuration file

### PR DESCRIPTION
**Pull request by waitlamp**
An Edited configuration file from XP-PEN Deco 01 v2 to support UGTABLET M708
Notice: there are two variant M708 with different Vendor ID Product ID
Tilt, Tablet button not work.
pen button, Tip, pressure work.

### CODE REVIEW

**Comment by Mrcubix** [comment]
I'm going to tell you right now, but from what i know, there is way more than 2 variants of the m708, most of them which are incompatible, this however look like it could work. so far, i've seen 6 different variants, 4 of them being :HVAN: and the 2 you provided.
Tilt is not supported yet (unless i'm missing something).
as for the tablets buttons, it's strange that they doesn't work, well, don't forget to edit TABLETS.md to add an entry,
compatibility: missing features
notes : tablet buttons doesn't work / multiple variants

**Comment by Mrcubix** [comment]
Kuuube told me about a parser you could try which is `OpenTabletDriver.Vendors.XP_Pen.XP_PenTiltReportParser`, try it, ler me know if express keys and tilt work

**Comment by AbstractQbit** [comment]
Please use the new format for configurations, look at other current configs for examples.

**Comment by waitlamp** [comment]
> Kuuube told me about a parser you could try which is `OpenTabletDriver.Vendors.XP_Pen.XP_PenTiltReportParser`, try it, let me know if express keys and tilt work

Yes, express keys and tilt now work well
Snipaste_2021-06-20_11-04-19



> Please use the new format for configurations, look at other current configs for examples.

I have tried to use new format for configurations, is the format correct now?


I used newest dev version in action, but key binding and windows ink plugin not work
so I tried

https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/897942452

M708 with this configuration work well in this version. windows ink, key binding, tilt, tablet button work.

please excuse PR title typing errors.

thanks!

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
