### PR TITLE
Revise actual area size of PTH-660 Bluetooth

### PR DESCRIPTION
**Pull request by Satanepigone**

### CODE REVIEW

**Comment by X9VoiD** [comment]
Do you have the tablet yourself? If yes please verify that the MaxX, and MaxY is indeed correct.

**Review by InfinityGhost — APPROVED** [review]
Consistent LPI/LPmm, so good catch.

**Comment by Satanepigone** [comment]
Yes, I have the tablet myself.
And I had made the same revision for previous repository.

Actually, the area size in PTH-660.json is correct.
but it is wrong in PTH-660 Bluetooth.json

https://github.com/OpenTabletDriver/OpenTabletDriver/pull/922

**Comment by Satanepigone** [comment]
> Yes, I have the tablet myself.
> And I had made the same revision for previous repository.
> 
> Actually, the area size in PTH-660.json is correct.
> but it is wrong in PTH-660 Bluetooth.json
> 
> #922

The MaxX, and MaxY are correct.

**Review by X9VoiD — APPROVED** [review]

**Comment by InfinityGhost** [comment]
Closing this PR in favor of #934 as it covers this one in scope.

**Pull request closed without merging**
