### PR TITLE
Fixed Windows key mappings

### PR DESCRIPTION
**Pull request by dreambottle**
Fix https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2350

### CODE REVIEW

**Comment by dreambottle** [comment]
this is a fix for https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2350

**Comment by Sublimelime** [comment]
This has minor merge conflicts after the DI rewrite. Probably easily fixable by @InfinityGhost pushing a commit to the branch (assuming the allow maintainers to edit box is checked).

**Comment by jamesbt365** [comment]
Should fix #1115

**Comment by dreambottle** [comment]
closing, I made a new branch with no conflicts

**Pull request closed without merging**
