### PR TITLE
Add support for XP-Pen Artist 10S

### PR DESCRIPTION
**Pull request by golandprog**
Diagnostics: [diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15241036/diag.txt)
Proof of work (Windows): https://youtu.be/STd6U_dqs84
Proof of work (Linux): 
image

### CODE REVIEW

**Comment by jamesbt365** [comment]
Configuration additions should include a diagnostic file alongside any other help you can provide proving the tablet configuration works, this also helps look for any potential configuration improvements in the future, so providing this information will be greatly helpful for getting this configuration merged.

**Comment by Ponywka** [comment]
> Configuration additions should include a diagnostic file alongside any other help you can provide proving the tablet configuration works, this also helps look for any potential configuration improvements in the future, so providing this information will be greatly helpful for getting this configuration merged.

Fixed!

**Review by jamesbt365 — COMMENTED** [review]
The jerky out of range parts in the video makes it a bit tricky for me to properly verify the data, is this just because you are actually close to the maximum hover or does this happen randomly/intermittently? I just want to confirm you are actually out of range at these points.

**Comment by jamesbt365** [comment]
Looking into what others have said, this is just broken and not mergeable in its current state.

**Comment by Ponywka** [comment]
> Looking into what others have said, this is just broken and not mergeable in its current state.

Hm... For me all works fine.

I see your previous comment before but I been swamped with work and forgot to answer it.

I can proof work right now (I've going to record video right now)

**Comment by Ponywka** [comment]
Proof with two branches: https://www.youtube.com/watch?v=nUWpgKPgsuo

**Comment by Ponywka** [comment]
> The jerky out of range parts in the video makes it a bit tricky for me to properly verify the data, is this just because you are actually close to the maximum hover or does this happen randomly/intermittently? I just want to confirm you are actually out of range at these points.

As I understand you talk about this part: https://youtu.be/STd6U_dqs84?t=18
In this moment I click the pen buttons. Because this tablet is old they can't operate position and buttons on the same time (even on original driver). It's my mistake for doing it so fast that you couldn't tell from the video what was going on.

**Comment by Ponywka** [comment]
Also as I understand you talk about this comment:

Originally commented by [meepster_836.9893 in Discord](https://discord.com/channels/615607687467761684/723399565780189234/1274440540183728139)
> I'm using an XP-Pen Artist 10S. I've got it "working" (I compiled the branch in the pull request for it, stumbled around and installed udev rules, disabled the wacom stuff).
>
>It's detected in OpenTabletDriver's UI and there seems to be no errors, but the pen doesn't do anything when I touch the screen. <...> Looking in the tablet debugger, the hex values are updating for the pen's position, buttons, pressure, all that, but the report type is just OutOfRangeReport.
>
><...>
>
>Bit of an update on that, I switched to windows and back and now the pen is doing it's thing properly.

To which the answer was given by [gonx in Discord](https://discord.com/channels/615607687467761684/723399565780189234/1274480978022109236)
>are you using the official windows driver
>if yes then the issue is that the initialization we're sending is incorrect
>some parts of the init might be enabled for as long as power is enabled as you've established

As I already replied in [Discord](https://discord.com/channels/615607687467761684/723399565780189234/1277424271471149147) this is happened for me when I used a proprietary driver. I don't know why, but the proprietary driver switches modes on the tablet itself and it starts sending data in a different format than the default. If you connect the tablet before the proprietary driver initializes the tablet, everything will work fine.

I couldn't switch the mode with any opcode after the proprietary driver did it , so the only way to fix this situation is to reconnect the tablet to the computer. This will reset the connection and the tablet will initialize again.

**Comment by Ponywka** [comment]
I've even used this configuration for drawing ~~(at least I tried)~~ and here's a proof of that (here I used the already compiled version with plugins like “VMultiMode” and “Windows Ink” installed

https://www.youtube.com/watch?v=nUWpgKPgsuo

**Comment by golandprog** [comment]
> Now that #3522 is merged, you need to rebase your configuration so that it passes the new tests (basically, any key with `null` or empty objects/arrays should not be included)
> 
> /e: it should be mentioned that given your above comments and proof, we can probably merge this as-is.

Done!

**Review by gonX — APPROVED** [review]
LGTM

**Pull request merged**
