### PR TITLE
[Backport] Add support for XP-Pen Artist 10S 

### PR DESCRIPTION
**Pull request by golandprog**
Diagnostics: [diag.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15244220/diag.json)
Backport of https://github.com/OpenTabletDriver/OpenTabletDriver/pull/3310

### CODE REVIEW

**Comment by Ponywka** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/8996795954/job/24823556039 is fixed

**Review by jamesbt365 — COMMENTED** [review]
Ditto of #3310, just want clarification on behaviour.

**Comment by Ponywka** [comment]
> Ditto of #3310, just want clarification on behaviour.

https://github.com/OpenTabletDriver/OpenTabletDriver/pull/3310#issuecomment-2309057896

**Comment by gonX** [comment]
Also needs a rebase here, since 0.6.x has a similar tablet bloat reduction change.

**Comment by golandprog** [comment]
> Also needs a rebase here, since 0.6.x has a similar tablet bloat reduction change.

Done!

**Review by gonX — APPROVED** [review]
LGTM

**Pull request merged**
